spring:
  application:
    name: media-service
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/media_service
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


CLOUDINARY_URL:  cloudinary://<api-key>:<api-secret>@<cloud_name>